- name: Variables
  hosts: localhost
  vars:
    Course: "AWS"
    Trainer: "Surya"
    Duration: "120Hrs"
  tasks:
    - name: variables print
      ansible.builtin.debug:
        msg: "Hi i joined {{Course}} couser and the {{Trainer}} trainer for the duration is {{Duration}}"