- name: from vars file
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: print from vars file
    ansible.builtin.debug:
      msg: "Hi print {{Course}} and {{Trainer}} and {{Duration}}"